sudo: false

language: node_js

node_js:
  - stable

install:
  - npm install
  
script:
  - npm run lint
  - npm run cover
  - npm run nsp
  - npm run build

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
   code_climate:
     repo_token: 9b560c614bf2fb292d5bf265a7b0bc8d201f4b339842cd8cd4adc95a015a6451

after_success:
  - npm run codeclimate-cover-submit
